# Generated by Django 2.2.7 on 2019-12-25 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qr_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_id', models.IntegerField(verbose_name='Номер QR')),
            ],
            options={
                'verbose_name': 'QR',
                'verbose_name_plural': 'QR',
            },
        ),
        migrations.CreateModel(
            name='Ulika_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUlika', models.IntegerField(default=0)),
                ('ulikaName', models.CharField(max_length=64, verbose_name='Название улики')),
                ('ulikaMesto', models.CharField(max_length=128, verbose_name='Место нахождения')),
                ('ulikaText', models.TextField(verbose_name='Описание предмета')),
                ('ulikaLupa', models.TextField(blank=True, verbose_name='Описание после изучения Лупой')),
                ('ulikaPhoto', models.TextField(blank=True, verbose_name='Описание после изучения Фотоаппаратом')),
                ('ulikaHim', models.TextField(blank=True, verbose_name='Описание после изучения Набором Криминалиста')),
                ('ulikaDictofon', models.TextField(blank=True, verbose_name='Описание после изучения Диктафоном')),
                ('ulikaImg', models.CharField(max_length=128, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Улика',
                'verbose_name_plural': 'Улики',
            },
        ),
        migrations.CreateModel(
            name='UserUlikaFead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.DateTimeField(auto_now_add=True, verbose_name='Время нахождения')),
                ('type_slot', models.CharField(choices=[('0', 'Нашел'), ('1', 'Лупа'), ('2', 'Диктофон'), ('3', 'Химический набор'), ('4', 'Сканер')], default=0, max_length=64, verbose_name='Чем поюзал')),
                ('id_Qr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newYearGame.Ulika_table', verbose_name='Найденный Qr')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Команда нашедшая qr-code улики')),
            ],
            options={
                'verbose_name': 'Поюзал улику',
                'verbose_name_plural': 'Поюзал улику',
            },
        ),
        migrations.CreateModel(
            name='Tools_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_slot', models.CharField(choices=[('1', 'Лупа'), ('2', 'Диктофон'), ('3', 'Химический набор'), ('4', 'Сканер'), ('5', 'Вода'), ('6', 'Гвоздь'), ('7', 'Йод'), ('8', 'Фенол Фталеин'), ('9', 'Керосин'), ('10', 'Мусор'), ('11', 'Мусор'), ('12', 'Мусор'), ('13', 'Мусор'), ('14', 'Мусор'), ('15', 'Мусор'), ('16', 'Мусор'), ('17', 'Мусор'), ('18', 'Мусор'), ('19', 'Мусор'), ('20', 'Мусор')], default=1, max_length=64, verbose_name='номер инструмента')),
                ('times', models.DateTimeField(auto_now_add=True, verbose_name='Время нахождения')),
                ('spent', models.BooleanField(default=True)),
                ('id_Qr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newYearGame.Qr_table', verbose_name='Найденный Qr')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Команда нашедшая qr-code')),
            ],
            options={
                'verbose_name': 'Найденный инструмент',
                'verbose_name_plural': 'База Найденных инструментов',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('location', models.CharField(blank=True, max_length=8, verbose_name='Класс')),
                ('komanda', models.TextField(verbose_name='Помощники')),
                ('time_fin', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания игры')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
