# Generated by Django 2.2.7 on 2019-12-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newYearGame', '0006_auto_20191222_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qr_table',
            options={'verbose_name': 'Найденный инструмент', 'verbose_name_plural': 'База Найденных инструментов'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='qr_table',
            name='qr_id',
            field=models.IntegerField(default=1, verbose_name='Номер QR'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='komanda',
            field=models.TextField(blank=True, verbose_name='Помощники'),
        ),
    ]
